In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep, strftime
from random import randint
import pandas as pd
import numpy as np

In [2]:
homepage = "https://www.tripadvisor.co.id/Attraction"
path = r"C:\Users\chiri\Downloads\chromedriver.exe"

driver = webdriver.Chrome(path)

In [5]:
df=pd.read_csv(r"C:\Users\chiri\Purwadhika\Final Project\dataset_others_nocuplicates.csv")

destination=df["Travel Destination"].values

In [6]:
df

,Travel Destination,Things to Do,Country Name,Location,Review Count
0,Pasanauri,"['Tur (1)', 'Tur dengan Perahu & Olahraga Air ...",Georgia,"Mtskheta-Mtianeti Region, Georgia",124
1,Zeda Gordi,"['Wisata Alam & Taman (1)', 'Cocok untuk Pasan...",Georgia,"Kutaisi, Georgia",409
2,Martivili,"['Pemandangan & Tengara (1)', 'Wisata Alam & T...",Georgia,"Samegrelo-Zemo Svaneti Region, Georgia",262
3,Tsinandali,"['Makanan & Minuman (3)', 'Museum (2)', 'Peman...",Georgia,"Kakheti Region, Georgia",465
4,Guria Region,"['Pemandangan & Tengara (4)', 'Wisata Alam & T...",Georgia,Georgia,937
...,...,...,...,...,...
4848,Tawala,"['Tur (6)', 'Tur dengan Perahu & Olahraga Air ...",Philippines,"Panglao, Filipina",6609
4849,Negros Occidental,"['Wisata Alam & Taman (65)', 'Pemandangan & Te...",Philippines,"Negros Island, Filipina",15452
4850,Bulacan Province,"['Pemandangan & Tengara (27)', 'Wisata Alam & ...",Philippines,"Central Luzon Region, Filipina",1761
4851,Bicol Region,"['Wisata Alam & Taman (124)', 'Pemandangan & T...",Philippines,"Luzon, Filipina",19573
4852,Anilao,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...",Philippines,"Batangas Province, Filipina",256

In [4]:
## Import dataset
# df = pd.read_csv("dataset_indo.csv")
# destination = df['Travel Destination'].values

In [3]:
df_destiny = []
todo = [] 
rating = []
reviewers = []
link = []
df_todo = []

In [8]:
destination[2]

'Martivili'

In [38]:
for destiny in destination[-1:]:
    print(destiny)
    driver.get(homepage)
    sleep(3)
    driver.find_element_by_xpath('//*[@id="component_1"]/div/div/form/input[1]').send_keys(destiny)
    sleep(5)
#     driver.find_element_by_xpath('//*[@id="component_1"]/div/div/form/input[1]').send_keys(Keys.ENTER)
    driver.find_element_by_class_name('_1dvyiAq4').click()
    sleep(2)
    
    todolist_2 = [] 
    todolist_link = []
    todolist = driver.find_elements_by_class_name('_3S09qsQh._30GXgBoj')
    for wtd in todolist:
        if wtd.text!="Lihat semua":
            todolist_2.append(wtd.text)
            todolist_link.append(wtd.get_attribute('href'))
    
    zipping = list(zip(todolist_2, todolist_link))

    #for 1st page
    for td, wtd in zipping:
        print(td)
        driver.get(wtd)
        obj = driver.find_elements_by_class_name('_25PvF8uO._2X44Y8hm')
        
        for card in obj:
            todo.append(td)
            df_destiny.append(destiny)
            df_todo.append(card.find_element_by_class_name('_1QKQOve4').text)
            link.append(card.find_element_by_class_name('_1QKQOve4').get_attribute('href'))
    
            try:
                rating.append(card.find_element_by_class_name('_3KcXyP0F.wxkjkcMP._1DZZGRFQ').get_attribute('title'))
            except:
                rating.append(np.nan)
            try:
                reviewers.append(card.find_element_by_class_name('HLvj7Lh5._1L-8ZIjh._2s3pPhGm').text)
            except:
                reviewers.append(np.nan)

        #Ini kalo mau pagenya lebih dari 1
        try:
            for page in range(1,11): #atur mau berapa page, kalo 1 berati ada 2 page totalnya. 
                driver.find_element_by_class_name('ui_button.nav.next.primary').click()
                obj = driver.find_elements_by_class_name('_25PvF8uO._2X44Y8hm')
                for card in obj:
                    todo.append(td)
                    df_destiny.append(destiny)
                    df_todo.append(card.find_element_by_class_name('_1QKQOve4').text)
                    link.append(card.find_element_by_class_name('_1QKQOve4').get_attribute('href'))
                    try:
                        rating.append(card.find_element_by_class_name('_3KcXyP0F.wxkjkcMP._1DZZGRFQ').get_attribute('title'))
                    except:
                        rating.append(np.nan)
                    try:
                        reviewers.append(card.find_element_by_class_name('HLvj7Lh5._1L-8ZIjh._2s3pPhGm').text)
                    except:
                        reviewers.append(np.nan)
        except:
            pass

Anilao
Tur (2)
Tur dengan Perahu & Olahraga Air (2)
Wisata Alam & Taman (2)
Aktivitas Luar Ruangan (2)

In [39]:
print(len(df_todo))
print(len(df_destiny))
print(len(rating))
print(len(reviewers))
print(len(link))
print(len(todo))

82260
82260
82260
82260
82260
82260

In [40]:
coba = pd.DataFrame({'destiny': df_destiny,
'todo': todo,
'todo_lagi': df_todo, 
'rating': rating,
'reviewers': reviewers,
'link': link})

In [41]:
coba

,destiny,todo,todo_lagi,rating,reviewers,link
0,Semboku,Pemandangan & Tengara (40),Samurai District,NaN,536 ulasan,https://www.tripadvisor.co.id/Attraction_Revie...
1,Semboku,Pemandangan & Tengara (40),Kakunodate,NaN,157 ulasan,https://www.tripadvisor.co.id/Attraction_Revie...
2,Semboku,Pemandangan & Tengara (40),Ishiguro Samurai House,NaN,139 ulasan,https://www.tripadvisor.co.id/Attraction_Revie...
3,Semboku,Pemandangan & Tengara (40),Aoyagi Samurai Manor Museum,NaN,177 ulasan,https://www.tripadvisor.co.id/Attraction_Revie...
4,Semboku,Pemandangan & Tengara (40),Hinokinaigawa Kasen Ryokuchi,NaN,75 ulasan,https://www.tripadvisor.co.id/Attraction_Revie...
...,...,...,...,...,...,...
82255,Anilao,Tur dengan Perahu & Olahraga Air (2),The Sicilian Reef and Dive Resort,NaN,3 ulasan,https://www.tripadvisor.co.id/Attraction_Revie...
82256,Anilao,Wisata Alam & Taman (2),Sombrero Island,NaN,16 ulasan,https://www.tripadvisor.co.id/Attraction_Revie...
82257,Anilao,Wisata Alam & Taman (2),Darangkulan Waterfall,NaN,NaN,https://www.tripadvisor.co.id/Attraction_Revie...
82258,Anilao,Aktivitas Luar Ruangan (2),Anilao Critters and Resorts,"5,0 dari 5 lingkaran",1 ulasan,https://www.tripadvisor.co.id/Attraction_Revie...
82259,Anilao,Aktivitas Luar Ruangan (2),The Sicilian Reef and Dive Resort,NaN,3 ulasan,https://www.tripadvisor.co.id/Attraction_Revie...

In [42]:
coba.to_csv("dataset_tahap2_others_details_2.csv", index=False)

In [44]:
toconcat=pd.read_csv("dataset_tahap2_others_details.csv")

In [47]:
df_complete=pd.concat([toconcat,coba]).reset_index().drop("index", axis=1)

In [52]:
df_complete=df_complete.rename(columns={"destiny":"Travel Destination",
                   "todo":"Things to Do",
                   "todo_lagi":"Spot / Vendor",
                   "reviewers":"Review Count",
                   "link":"Link"})

In [53]:
df_complete.to_csv("dataset_spot_others.csv", index=False)