In [13]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [14]:
df=pd.read_csv("dataset_baseline.csv")

In [15]:
df[df["Travel Destination"]=="Tuban"]

,Country Name,Travel Destination,Checking,Things to Do,Location,Review Count
55,Indonesia,Tuban,Tuban,tur aktivitasluarruangan transportasi spadanke...,"Kuta, Indonesia",20552
56,Indonesia,Tuban,Tuban,tur aktivitasluarruangan transportasi spadanke...,"Jawa Timur, Indonesia",313

In [16]:
df=df.drop_duplicates(["Travel Destination","Location","Review Count"],keep="first", inplace=False)

In [17]:
df=df.reset_index().drop("index",axis=1)

In [18]:
cv = CountVectorizer()
cv_result = cv.fit_transform(df['Things to Do'])

In [19]:
cv.get_feature_names()

['acara',
 'aktivitasluarruangan',
 'bagussaathujan',
 'berjiwapetualang',
 'cocokuntukanakanak',
 'cocokuntukkelompokbesar',
 'cocokuntukpasangan',
 'cocokuntukpenggemaraktivitasekstrem',
 'hargaterjangkau',
 'hiburandanpermainan',
 'hiburanmalam',
 'kasinodanperjudian',
 'kebunbinatangdanakuarium',
 'konserdanpertunjukan',
 'kursusdansanggar',
 'lokasibulanmadu',
 'makanandanminuman',
 'masukgratis',
 'museum',
 'pemandangandantengara',
 'spadankebugaran',
 'sumberinformasiwisatawan',
 'tamanairdantamanhiburan',
 'tempatbelanja',
 'tempatyangbelumpopuler',
 'transportasi',
 'tur',
 'turdenganperahudanolahragaair',
 'wisataalamdantaman']

In [20]:
len(cv.get_feature_names())

29

In [21]:
cv_df = pd.DataFrame(cv_result.todense(),columns= cv.get_feature_names(),index=df['Travel Destination'])
cv_df

,acara,aktivitasluarruangan,bagussaathujan,berjiwapetualang,cocokuntukanakanak,cocokuntukkelompokbesar,cocokuntukpasangan,cocokuntukpenggemaraktivitasekstrem,hargaterjangkau,hiburandanpermainan,...,pemandangandantengara,spadankebugaran,sumberinformasiwisatawan,tamanairdantamanhiburan,tempatbelanja,tempatyangbelumpopuler,transportasi,tur,turdenganperahudanolahragaair,wisataalamdantaman
Travel Destination,,,,,,,,,,,,,,,,,,,,,
Bintan,0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Seminyak,0,1,1,1,1,1,1,1,1,1,...,1,1,0,0,1,1,1,1,1,1
Bali,0,1,1,1,1,1,1,1,1,1,...,1,1,0,1,1,1,1,1,1,1
Ubud,0,1,1,1,1,1,1,1,1,1,...,1,1,1,0,1,1,1,1,1,1
Jakarta,0,1,1,1,1,1,1,1,1,1,...,1,1,0,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tawala,0,1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,1,1,1
Negros Occidental,1,1,1,0,1,1,1,1,1,1,...,1,1,0,1,1,0,1,1,1,1
Bulacan Province,0,1,1,1,1,1,1,0,1,0,...,1,1,0,1,1,0,0,1,1,1
Bicol Region,0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Anilao,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1

In [23]:
cos_sin = cosine_similarity(cv_result)

In [24]:
pd.DataFrame(cos_sin, index=df["Travel Destination"], columns=df["Travel Destination"])

Travel Destination,Bintan,Seminyak,Bali,Ubud,Jakarta,Kuta,Kuta,Legian,Yogyakarta,Yogyakarta,...,Badian,Tagum City,Dasmarinas City,Sabang,San Vicente,Tawala,Negros Occidental,Bulacan Province,Bicol Region,Anilao
Travel Destination,,,,,,,,,,,,,,,,,,,,,
Bintan,1.000000,0.898146,0.920000,0.920000,0.920000,0.920000,0.920000,0.917463,0.920000,0.920000,...,0.721110,0.748331,0.603023,0.824621,0.848528,0.721110,0.829228,0.750000,0.960000,0.400000
Seminyak,0.898146,1.000000,0.979796,0.979796,0.979796,0.979796,0.979796,0.978945,0.979796,0.979796,...,0.679366,0.763763,0.677003,0.841625,0.866025,0.735980,0.801784,0.765466,0.898146,0.408248
Bali,0.920000,0.979796,1.000000,0.960000,1.000000,1.000000,1.000000,0.959166,1.000000,1.000000,...,0.721110,0.748331,0.663325,0.824621,0.848528,0.721110,0.829228,0.800000,0.920000,0.400000
Ubud,0.920000,0.979796,0.960000,1.000000,0.960000,0.960000,0.960000,0.959166,0.960000,0.960000,...,0.665640,0.748331,0.663325,0.824621,0.848528,0.721110,0.785584,0.750000,0.920000,0.400000
Jakarta,0.920000,0.979796,1.000000,0.960000,1.000000,1.000000,1.000000,0.959166,1.000000,1.000000,...,0.721110,0.748331,0.663325,0.824621,0.848528,0.721110,0.829228,0.800000,0.920000,0.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tawala,0.721110,0.735980,0.721110,0.721110,0.721110,0.721110,0.721110,0.751809,0.721110,0.721110,...,0.846154,0.741249,0.418121,0.807207,0.784465,1.000000,0.665750,0.693375,0.721110,0.554700
Negros Occidental,0.829228,0.801784,0.829228,0.785584,0.829228,0.829228,0.829228,0.819028,0.829228,0.829228,...,0.726273,0.816497,0.723747,0.793884,0.771517,0.665750,1.000000,0.818317,0.872872,0.436436
Bulacan Province,0.750000,0.765466,0.800000,0.750000,0.800000,0.800000,0.800000,0.781929,0.800000,0.800000,...,0.693375,0.801784,0.753778,0.788241,0.707107,0.693375,0.818317,1.000000,0.800000,0.500000
Bicol Region,0.960000,0.898146,0.920000,0.920000,0.920000,0.920000,0.920000,0.917463,0.920000,0.920000,...,0.721110,0.748331,0.663325,0.824621,0.848528,0.721110,0.872872,0.800000,1.000000,0.400000
Anilao,0.400000,0.408248,0.400000,0.400000,0.400000,0.400000,0.400000,0.417029,0.400000,0.400000,...,0.554700,0.534522,0.301511,0.485071,0.471405,0.554700,0.436436,0.500000,0.400000,1.000000

In [27]:
df[df['Travel Destination'] == "Ubud"].index[0]

3

In [28]:
pd.Series(cos_sin[3])

0       0.920000
1       0.979796
2       0.960000
3       1.000000
4       0.960000
          ...
5172    0.721110
5173    0.785584
5174    0.750000
5175    0.920000
5176    0.400000
Length: 5177, dtype: float64

In [40]:
cv_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5177 entries, Bintan to Anilao
Data columns (total 29 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   acara                                5177 non-null   int64
 1   aktivitasluarruangan                 5177 non-null   int64
 2   bagussaathujan                       5177 non-null   int64
 3   berjiwapetualang                     5177 non-null   int64
 4   cocokuntukanakanak                   5177 non-null   int64
 5   cocokuntukkelompokbesar              5177 non-null   int64
 6   cocokuntukpasangan                   5177 non-null   int64
 7   cocokuntukpenggemaraktivitasekstrem  5177 non-null   int64
 8   hargaterjangkau                      5177 non-null   int64
 9   hiburandanpermainan                  5177 non-null   int64
 10  hiburanmalam                         5177 non-null   int64
 11  kasinodanperjudian                   5177 non-null   int64
 12  kebunbinatangdanakuarium             5177 non-null   int64
 13  konserdanpertunjukan                 5177 non-null   int64
 14  kursusdansanggar                     5177 non-null   int64
 15  lokasibulanmadu                      5177 non-null   int64
 16  makanandanminuman                    5177 non-null   int64
 17  masukgratis                          5177 non-null   int64
 18  museum                               5177 non-null   int64
 19  pemandangandantengara                5177 non-null   int64
 20  spadankebugaran                      5177 non-null   int64
 21  sumberinformasiwisatawan             5177 non-null   int64
 22  tamanairdantamanhiburan              5177 non-null   int64
 23  tempatbelanja                        5177 non-null   int64
 24  tempatyangbelumpopuler               5177 non-null   int64
 25  transportasi                         5177 non-null   int64
 26  tur                                  5177 non-null   int64
 27  turdenganperahudanolahragaair        5177 non-null   int64
 28  wisataalamdantaman                   5177 non-null   int64
dtypes: int64(29)
memory usage: 1.2+ MB

In [29]:
cv_df

,acara,aktivitasluarruangan,bagussaathujan,berjiwapetualang,cocokuntukanakanak,cocokuntukkelompokbesar,cocokuntukpasangan,cocokuntukpenggemaraktivitasekstrem,hargaterjangkau,hiburandanpermainan,...,pemandangandantengara,spadankebugaran,sumberinformasiwisatawan,tamanairdantamanhiburan,tempatbelanja,tempatyangbelumpopuler,transportasi,tur,turdenganperahudanolahragaair,wisataalamdantaman
Travel Destination,,,,,,,,,,,,,,,,,,,,,
Bintan,0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Seminyak,0,1,1,1,1,1,1,1,1,1,...,1,1,0,0,1,1,1,1,1,1
Bali,0,1,1,1,1,1,1,1,1,1,...,1,1,0,1,1,1,1,1,1,1
Ubud,0,1,1,1,1,1,1,1,1,1,...,1,1,1,0,1,1,1,1,1,1
Jakarta,0,1,1,1,1,1,1,1,1,1,...,1,1,0,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tawala,0,1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,1,1,1
Negros Occidental,1,1,1,0,1,1,1,1,1,1,...,1,1,0,1,1,0,1,1,1,1
Bulacan Province,0,1,1,1,1,1,1,0,1,0,...,1,1,0,1,1,0,0,1,1,1
Bicol Region,0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Anilao,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1

In [25]:
def get_recomendation(place):
    index_to_search = df[df['Travel Destination'] == place].index[0]
    place_similar = pd.Series(cos_sin[index_to_search])
    index_similar = place_similar.sort_values(ascending=False).index
    
#     for i in 
#     return df.loc[index_similar]['Travel Destination']
    return index_similar

In [16]:
df[df['Travel Destination'] == "Seoul"].index[0]

4806

In [18]:
cos_sin[df[df['Travel Destination'] == "Seoul"].index[0]]

array([0.92     , 0.9797959, 0.96     , ..., 0.75     , 0.92     ,
       0.4      ])

In [13]:
df[(df["Country Name"]=="Indonesia") & (df["Travel Destination"]=="Jakarta")]

,Country Name,Travel Destination,Checking,Things to Do,Location,Review Count
4,Indonesia,Jakarta,Jakarta,tur tempatbelanja spadankebugaran aktivitaslua...,"Jawa, Indonesia",339358

In [14]:
get_recomendation("Seoul")

Int64Index([3617,  590,  601,  608,  610, 4806, 4804, 4800,  612, 5055,
            ...
            1835, 2570, 3422, 3421, 4646, 1648, 1647, 1646, 2300, 5119],
           dtype='int64', length=5177)

In [153]:
prefer=get_recomendation('Seoul')

In [154]:
recomm_id=[]

for i in prefer:
    if (df["Country Name"].iloc[i])=="Indonesia":
        recomm_id.append (i)

In [155]:
for i in recomm_id[0:10]:
    print(df.loc[i]["Travel Destination"],"---",df.loc[i]["Location"])

Sanur --- Denpasar, Indonesia
Ubud --- Gianyar Regency, Indonesia
Seminyak --- Kecamatan Kuta, Indonesia
Kuta Utara --- Bali, Indonesia
Kecamatan Kuta --- Bali, Indonesia
Buleleng --- Kabupaten Buleleng, Indonesia
Buleleng --- Buleleng, Indonesia
Bogor --- Jawa Barat, Indonesia
Denpasar --- Bali, Indonesia
Canggu --- Kuta Utara, Indonesia

## TRIAL ONLY

In [42]:
user_data={'acara':0,
 'aktivitasluarruangan':1,
 'bagussaathujan':0,
 'berjiwapetualang':1,
 'cocokuntukanakanak':0,
 'cocokuntukkelompokbesar':0,
 'cocokuntukpasangan':1,
 'cocokuntukpenggemaraktivitasekstrem':1,
 'hargaterjangkau':0,
 'hiburandanpermainan':0,
 'hiburanmalam':0,
 'kasinodanperjudian':1,
 'kebunbinatangdanakuarium':1,
 'konserdanpertunjukan':0,
 'kursusdansanggar':0,
 'lokasibulanmadu':0,
 'makanandanminuman':0,
 'masukgratis':0,
 'museum':0,
 'pemandangandantengara':1,
 'spadankebugaran':0,
 'sumberinformasiwisatawan':0,
 'tamanairdantamanhiburan':0,
 'tempatbelanja':0,
 'tempatyangbelumpopuler':1,
 'transportasi':0,
 'tur':1,
 'turdenganperahudanolahragaair':1,
 'wisataalamdantaman':1}

In [48]:
new=pd.Series(data=user_data, name="user")

In [49]:
cv_df.append(new, ignore_index=False)

,acara,aktivitasluarruangan,bagussaathujan,berjiwapetualang,cocokuntukanakanak,cocokuntukkelompokbesar,cocokuntukpasangan,cocokuntukpenggemaraktivitasekstrem,hargaterjangkau,hiburandanpermainan,...,pemandangandantengara,spadankebugaran,sumberinformasiwisatawan,tamanairdantamanhiburan,tempatbelanja,tempatyangbelumpopuler,transportasi,tur,turdenganperahudanolahragaair,wisataalamdantaman
Travel Destination,,,,,,,,,,,,,,,,,,,,,
Bintan,0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Seminyak,0,1,1,1,1,1,1,1,1,1,...,1,1,0,0,1,1,1,1,1,1
Bali,0,1,1,1,1,1,1,1,1,1,...,1,1,0,1,1,1,1,1,1,1
Ubud,0,1,1,1,1,1,1,1,1,1,...,1,1,1,0,1,1,1,1,1,1
Jakarta,0,1,1,1,1,1,1,1,1,1,...,1,1,0,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Negros Occidental,1,1,1,0,1,1,1,1,1,1,...,1,1,0,1,1,0,1,1,1,1
Bulacan Province,0,1,1,1,1,1,1,0,1,0,...,1,1,0,1,1,0,0,1,1,1
Bicol Region,0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Anilao,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
user,0,1,0,1,0,0,1,1,0,0,...,1,0,0,0,0,1,0,1,1,1