In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv("dataset_indo_engineered.csv")
df2=pd.read_csv("dataset_others_engineered.csv")

In [4]:
df1

,Country Name,Travel Destination,Checking,Things to Do,Location,Review Count
0,Indonesia,Bintan,Bintan,tur aktivitasluarruangan transportasi turdenga...,"Bintan Regency, Indonesia",25006
1,Indonesia,Seminyak,Seminyak,tur spadankebugaran aktivitasluarruangan tempa...,"Kecamatan Kuta, Indonesia",451212
2,Indonesia,Bali,Bali,tur aktivitasluarruangan turdenganperahudanola...,Indonesia,2998882
3,Indonesia,Ubud,Ubud,tur aktivitasluarruangan spadankebugaran trans...,"Gianyar Regency, Indonesia",610495
4,Indonesia,Jakarta,Jakarta,tur tempatbelanja spadankebugaran aktivitaslua...,"Jawa, Indonesia",339358
...,...,...,...,...,...,...
321,Indonesia,Toyapakeh,Toyapakeh,tur turdenganperahudanolahragaair aktivitaslua...,"Nusa Penida, Indonesia",742
322,Indonesia,Singakerta,Singakerta,spadankebugaran tur kursusdansanggar hiburanda...,"Ubud, Indonesia",2019
323,Indonesia,Guwang,Guwang,wisataalamdantaman cocokuntukpasangan hargater...,"Sukawati, Indonesia",343
324,Indonesia,Singapadu Kaler,Singapadu Kaler,tur turdenganperahudanolahragaair aktivitaslua...,"Sukawati, Indonesia",309
325,Indonesia,Batu Karas,Batu Karas,tur turdenganperahudanolahragaair aktivitaslua...,"Jawa Barat, Indonesia",206

In [5]:
df2

,Travel Destination,Checking,Things to Do,Country Name,Location,Review Count
0,Pasanauri,Pasanauri,tur turdenganperahudanolahragaair aktivitaslua...,Georgia,"Mtskheta-Mtianeti Region, Georgia",124
1,Zeda Gordi,Zeda Gordi,wisataalamdantaman cocokuntukpasangan hargater...,Georgia,"Kutaisi, Georgia",409
2,Martivili,Martivili,pemandangandantengara wisataalamdantaman cocok...,Georgia,"Samegrelo-Zemo Svaneti Region, Georgia",262
3,Tsinandali,Tsinandali,makanandanminuman museum pemandangandantengara...,Georgia,"Kakheti Region, Georgia",465
4,Guria Region,Guria Region,pemandangandantengara wisataalamdantaman aktiv...,Georgia,Georgia,937
...,...,...,...,...,...,...
5290,Tawala,Tawala,tur turdenganperahudanolahragaair aktivitaslua...,Philippines,"Panglao, Filipina",6609
5291,Negros Occidental,Negros Occidental,wisataalamdantaman pemandangandantengara aktiv...,Philippines,"Negros Island, Filipina",15452
5292,Bulacan Province,Bulacan Province,pemandangandantengara wisataalamdantaman taman...,Philippines,"Central Luzon Region, Filipina",1761
5293,Bicol Region,Bicol Region,wisataalamdantaman pemandangandantengara aktiv...,Philippines,"Luzon, Filipina",19573
5294,Anilao,Anilao,tur turdenganperahudanolahragaair wisataalamda...,Philippines,"Batangas Province, Filipina",256

In [6]:
df_complete=pd.concat([df1,df2])

In [7]:
df_complete.to_csv("dataset_baseline.csv", index=False)